name: Fix Template
description: Fix 또는 Hotfix 사항이 있을 때 사용하는 템플릿
title: "[Fix] Fix 이슈 제목"
labels: ["♻️Refactor"]

body:
  - type: input
    id: related-bug
    attributes:
      label: ♻️ Related Bug(Optaional)
      description: 관련된 버그 이슈
      placeholder: "ex. #32, #23"
    validations:
      required: false
  - type: textarea
    id: before-fix
    attributes:
      label: ♻️ Current State
      description: Fix 전(현재) 내용
      placeholder: "닉네임 설정 시, 공백을 Submit하면 아무런 반응 없음"
    validations:
      required: true
  - type: textarea
    id: after-fix
    attributes:
      label: ♻️ After State
      description: Fix 후 내용
      placeholder: "닉네임 설정 시, 공백을 Submit하면 Alert 표시"
    validations:
      required: true

